//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamCleaner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RamCleaner.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App started. Ready..
        /// </summary>
        public static string AppStarted {
            get {
                return ResourceManager.GetString("AppStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe RAM Cleaner.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Clean.
        /// </summary>
        public static string AutoClean {
            get {
                return ResourceManager.GetString("AutoClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available RAM.
        /// </summary>
        public static string AvailableRAM {
            get {
                return ResourceManager.GetString("AvailableRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached (Standby).
        /// </summary>
        public static string CachedStandby {
            get {
                return ResourceManager.GetString("CachedStandby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning....
        /// </summary>
        public static string Cleaning {
            get {
                return ResourceManager.GetString("Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Memory Now.
        /// </summary>
        public static string CleanMemoryNow {
            get {
                return ResourceManager.GetString("CleanMemoryNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committed / Limit.
        /// </summary>
        public static string CommittedLimit {
            get {
                return ResourceManager.GetString("CommittedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log.
        /// </summary>
        public static string EventLog {
            get {
                return ResourceManager.GetString("EventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        public static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freed: {0:F0} MB (Processed {1} apps).
        /// </summary>
        public static string FreedMessage {
            get {
                return ResourceManager.GetString("FreedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Processes.
        /// </summary>
        public static string IgnoredProcesses {
            get {
                return ResourceManager.GetString("IgnoredProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Cleaned.
        /// </summary>
        public static string MemoryCleaned {
            get {
                return ResourceManager.GetString("MemoryCleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to clean.
        /// </summary>
        public static string ReadyToClean {
            get {
                return ResourceManager.GetString("ReadyToClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on Startup.
        /// </summary>
        public static string RunOnStartup {
            get {
                return ResourceManager.GetString("RunOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Processes.
        /// </summary>
        public static string RunningProcesses {
            get {
                return ResourceManager.GetString("RunningProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show after Auto Clean.
        /// </summary>
        public static string ShowAfterAutoClean {
            get {
                return ResourceManager.GetString("ShowAfterAutoClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show after Manual Clean.
        /// </summary>
        public static string ShowAfterManualClean {
            get {
                return ResourceManager.GetString("ShowAfterManualClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategies.
        /// </summary>
        public static string Strategies {
            get {
                return ResourceManager.GetString("Strategies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully freed {0:F0} MB of RAM..
        /// </summary>
        public static string SuccessfullyFreed {
            get {
                return ResourceManager.GetString("SuccessfullyFreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Memory Status.
        /// </summary>
        public static string SystemMemoryStatus {
            get {
                return ResourceManager.GetString("SystemMemoryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Physical RAM.
        /// </summary>
        public static string TotalPhysicalRAM {
            get {
                return ResourceManager.GetString("TotalPhysicalRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage &gt;.
        /// </summary>
        public static string UsageGreater {
            get {
                return ResourceManager.GetString("UsageGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage History (60s).
        /// </summary>
        public static string UsageHistory {
            get {
                return ResourceManager.GetString("UsageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used RAM.
        /// </summary>
        public static string UsedRAM {
            get {
                return ResourceManager.GetString("UsedRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitelist.
        /// </summary>
        public static string Whitelist {
            get {
                return ResourceManager.GetString("Whitelist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
    }
}